# This is a basic workflow to help you get started with Actions

name: Webapp Test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Setup Node
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install node modules
      - name: Install node modules
        run: cd webapp; npm install

      # Test the web app
      - name: Test the web app
        run: cd webapp; npm run coverage
