# This is a basic workflow to help you get started with Actions

name: Default Test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events when there are no changes made to the functions directory or the webapp directory
  pull_request:
    paths-ignore:
      - "@types/**"
      - "functions/**"
      - "webapp/**"

  # Triggers the workflow on push events to main when there are no changes made to the functions directory or the webapp directory
  # push:
  #   branches:
  #     - "main"
  #   paths-ignore:
  #    - "functions/**"
  #    - "webapp/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v2
